// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-9mj_jv50ekzD-3eWE22KmZtLnA1atbU',
    appId: '1:667204274859:android:3747a706b534f88897c5ee',
    messagingSenderId: '667204274859',
    projectId: 'note-application-97107',
    storageBucket: 'note-application-97107.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3hdNSbcWirAEQcfDWkrPwu6_3SOFQFBo',
    appId: '1:667204274859:ios:2f6b0c2c74e447de97c5ee',
    messagingSenderId: '667204274859',
    projectId: 'note-application-97107',
    storageBucket: 'note-application-97107.firebasestorage.app',
    androidClientId: '667204274859-ik82ahqds5atd3nmfv2ibm74ct13h1lg.apps.googleusercontent.com',
    iosClientId: '667204274859-dldu21nnniid1bi2jbqqvfljnqcd7i5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApplication',
  );

}